services:
    Asdoria\SyliusBulkEditPlugin\Controller\BulkEditController:
        public: true
        arguments:
            $twig: '@twig'
            $formFactory: '@form.factory'
            $eventDispatcher: '@event_dispatcher'
