services:
    Asdoria\SyliusBulkEditPlugin\Twig\AttributeByLocaleExtension:
        arguments:
            $helper: '@Asdoria\SyliusBulkEditPlugin\Templating\Helper\AttributeByLocaleHelper'
        tags:
            - { name: twig.extension }
