services:
    asdoria_bulk_edit.action.add_product_taxon:
        class: Asdoria\SyliusBulkEditPlugin\Action\AddProductTaxonAction
        public: true
        arguments:
            $productTaxonFactory: '@sylius.factory.product_taxon'
        calls:
            - [setTaxonRepository, ['@sylius.repository.taxon']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
        tags:
            -   name: asdoria_bulk_edit.action
                type: !php/const Asdoria\SyliusBulkEditPlugin\Action\AddProductTaxonAction::ADD_PRODUCT_TAXON
                type_identifier: !php/const Asdoria\SyliusBulkEditPlugin\Action\ResourceActionInterface::PRODUCT_CONTEXT
                label: asdoria_bulk_edit.form.add_product_taxon
                form_type: Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\TaxonsConfigurationType

    asdoria_bulk_edit.action.remove_taxon:
        class: Asdoria\SyliusBulkEditPlugin\Action\RemoveProductTaxonAction
        public: true
        calls:
            - [setTaxonRepository, ['@sylius.repository.taxon']]
        tags:
            -   name: asdoria_bulk_edit.action
                type: !php/const Asdoria\SyliusBulkEditPlugin\Action\RemoveProductTaxonAction::REMOVE_PRODUCT_TAXON
                type_identifier: !php/const Asdoria\SyliusBulkEditPlugin\Action\ResourceActionInterface::PRODUCT_CONTEXT
                label: asdoria_bulk_edit.form.remove_product_taxon
                form_type: Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\TaxonsConfigurationType

    asdoria_bulk_edit.action.set_main_taxon:
        class: Asdoria\SyliusBulkEditPlugin\Action\SetMainTaxonAction
        public: true
        calls:
            - [setTaxonRepository, ['@sylius.repository.taxon']]
        tags:
            -   name: asdoria_bulk_edit.action
                type: !php/const Asdoria\SyliusBulkEditPlugin\Action\SetMainTaxonAction::SET_MAIN_TAXON
                type_identifier: !php/const Asdoria\SyliusBulkEditPlugin\Action\ResourceActionInterface::PRODUCT_CONTEXT
                label: asdoria_bulk_edit.form.set_main_taxon
                form_type: Asdoria\SyliusBulkEditPlugin\Form\Type\Configuration\TaxonConfigurationType
