imports:
    - { resource: "../grids/*.yaml" }
    - { resource: "actions_config.yaml" }

doctrine_migrations:
    migrations_paths:
        'Asdoria\Bundle\BulkEditBundle\Migrations': '@AsdoriaBulkEditBundle/Migrations'

sylius_ui:
    events:
        sylius.admin.product.index.javascripts:
            blocks:
                scripts:
                    template: "@AsdoriaBulkEdit/_javascripts/Product/_javascripts.html.twig"
                    priority: 10
        sylius.admin.product.index.stylesheets:
            blocks:
                scripts:
                    template: "@AsdoriaBulkEdit/_stylesheets/Product/_stylesheets.html.twig"
                    priority: 10

framework:
    assets:
        packages:
            asdoria_sylius_bulk_edit_plugin:
                base_path: '/bundles/asdoriasyliusbulkeditplugin'
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            bulk_edit: '%env(MESSENGER_TRANSPORT_BULK_EDIT_DSN)%'
        #            options:
        #                queue_name: bulk_edit
        # failed: 'doctrine://default?queue_name=failed'
        # sync: 'sync://'

        routing:
            # route all messages that extend this example base class or interface
            'Asdoria\SyliusBulkEditPlugin\Message\BulkEditNotificationInterface': bulk_edit

        buses:
            asdoria_bulk_edit.bus:
                middleware:
                    # each time a message is handled, the Doctrine connection
                    # is "pinged" and reconnected if it's closed. Useful
                    # if your workers run for a long time and the database
                    # connection is sometimes lost
                    - doctrine_ping_connection
                    # After handling, the Doctrine connection is closed,
                    # which can free up database connections in a worker,
                    # instead of keeping them open forever
                    - doctrine_close_connection
                    # wraps all handlers in a single Doctrine transaction
                    # handlers do not need to call flush() and an error
                    # in any handler will cause a rollback
                    - doctrine_transaction

